GLOBAL_BLOCKED_PATTERNS = [
    "/premium/",
    "/feed/",
    "/messaging/",
    "/mynetwork/",
    "/notifications/",
    "/help/",
    "/widgets/",
    "/job-alert-email-unsubscribe",
    "/psettings/",
    "/jobs/alerts",
    "/jobs/search",
    "/jobs/search-results",
    "/login",
    "/signup",
    "/career-advice",
    "/companies",
    "/salaries",
    "apps.microsoft.com",
    "itunes.apple.com",
    "play.google.com",
    "/register",
    "/salary",
    "/blog",
    "/privacy",
    "/terms",
    "/unsubscribe",
    "/settings",
    "/profile",
    "/messages",
]


def generic_portal(domains, job_path_patterns=None):
    return {
        "domains": domains,
        "email_senders": domains,
        "job_path_patterns": job_path_patterns or [],
        "blocked_patterns": [],
        "requires_login": False,
        "profile_dir": None,
        "scraper": "generic",
    }


PORTALS = {
    "linkedin": {
        "domains": ["linkedin.com"],
        "email_senders": ["linkedin.com","jobalerts-noreply@linkedin.com","jobs-listings@linkedin.com","jobs-noreply@linkedin.com",],
        "job_path_patterns": [
            r"/comm/jobs/view/\d+(?:/|$)",
            r"/jobs/view/\d+(?:/|$)",
        ],
        "blocked_patterns": ["/login", "/feed", "/jobs/search", "/jobs/alerts"],
        "requires_login": True,
        "profile_dir": "data/gmail-agent/browser_profiles/linkedin",
        "scraper": "linkedin",
    },
    "indeed": {
        "domains": ["indeed.com"],
        "email_senders": ["indeed.com", "jobalert.indeed.com","donotreply@indeed.com","alert@indeed.com"],
        "job_path_patterns": [
            r"/viewjob(?:/|$)",
            r"/rc/clk(?:/|$)",
            r"/pagead/clk(?:/|$)",
        ],
        "blocked_patterns": ["/career-advice", "/companies", "/q-"],
        "requires_login": False,
        "profile_dir": "data/gmail-agent/browser_profiles/indeed",
        "scraper": "indeed",
    },
    "bayt": {
        "domains": ["bayt.com"],
        "email_senders": ["bayt.com","notify@bayt.com"],
        "job_path_patterns": [
            r"/(?:en|ar)/(?:[^/]+/)?jobs/[^/]+-\d+(?:/|$)",
        ],
        "blocked_patterns": [
            "/login",
            "/register",
            "/myworkspace",
            "/jobseeker/",
            "/landing-page/",
            "/blog/",
            "/pages/",
            "/privacy",
            "/terms",
            "/cv",
            "cv_freshness",
            "js_cvupdate",
            "usertoken",
        ],
        "requires_login": False,
        "profile_dir": "data/gmail-agent/browser_profiles/bayt",
        "scraper": "bayt",
    },
    "naukri": {
        "domains": ["naukri.com"],
        "email_senders": ["naukri.com","naukrinewalerts@naukri.com","naukrisearchalerts@naukri.com"],
        "job_path_patterns": [r"/job-listings"],
        "blocked_patterns": ["/login", "/registration", "/mnjuser"],
        "requires_login": False,
        "profile_dir": "data/gmail-agent/browser_profiles/naukri",
        "scraper": "naukri",
    },
    "glassdoor": {
        "domains": ["glassdoor.com"],
        "domain_patterns": [
            r"(^|\.)glassdoor\.(?:com|[a-z]{2}|co\.[a-z]{2}|com\.[a-z]{2})$",
        ],
        "email_senders": ["glassdoor.com", "noreply@glassdoor.com"],
        "job_path_patterns": [
            r"/job-listing/",
            r"/partner/jobListing\.htm$",
            r"/Job/[^/]+\.htm$",
        ],
        "blocked_patterns": [
            "/assets/",
            "/Community/",
            "/Interview/",
            "/about/",
            "/member/",
            "/profile/",
            ".png",
            ".jpg",
            ".jpeg",
            ".gif",
            ".webp",
        ],
        "requires_login": False,
        "profile_dir": "data/gmail-agent/browser_profiles/glassdoor",
        "scraper": "glassdoor",
    },
    "gulftalent": {
        "domains": ["gulftalent.com"],
        "email_senders": ["gulftalent.com"],
        "job_path_patterns": [r"/[^/]+/jobs/[^/]+-\d+(?:/|$)"],
        "blocked_patterns": [],
        "requires_login": False,
        "profile_dir": "data/gmail-agent/browser_profiles/gulftalent",
        "scraper": "gulftalent",
    },
    "iimjobs": {
        "domains": ["iimjobs.com"],
        "email_senders": ["iimjobs.com"],
        "job_path_patterns": [r"/j/[^/]+-\d+(?:/|$)"],
        "blocked_patterns": [],
        "requires_login": False,
        "profile_dir": "data/gmail-agent/browser_profiles/iimjobs",
        "scraper": "iimjobs",
    },
    "naukrigulf": {
        "domains": ["naukrigulf.com"],
        "email_senders": ["naukrigulf.com"],
        "job_path_patterns": [],
        "blocked_patterns": [],
        "requires_login": False,
        "profile_dir": "data/gmail-agent/browser_profiles/naukrigulf",
        "scraper": "naukrigulf",
    },
    "foundit": {
        "domains": [
            "foundit.in",
            "founditgulf.com",
            "foundit.hk",
            "foundit.sg",
            "foundit.com.ph",
            "foundit.my",
            "foundit.id",
            "monster.com.vn",
            "monster.co.th",
        ],
        "email_senders": [
            "foundit.in",
            "founditgulf.com",
            "foundit.hk",
            "foundit.sg",
            "foundit.com.ph",
            "foundit.my",
            "foundit.id",
            "monster.com.vn",
            "monster.co.th",
        ],
        "job_path_patterns": [r"/job/"],
        "blocked_patterns": [
            "/login",
            "/register",
            "/career-advice",
            "/companies",
            "/salaries",
            "/rio/login",
            "/info/",
        ],
        "requires_login": False,
        "headless": False,
        "profile_dir": "data/gmail-agent/browser_profiles/foundit",
        "scraper": "foundit",
    },
    "greenhouse": generic_portal(
        ["greenhouse.io"],
        [r"/(?:[^/]+/)?jobs/\d+(?:/|$)"],
    ),
    "lever": generic_portal(
        ["lever.co"],
        [r"/[^/]+/[0-9a-f-]{8,}(?:/|$)"],
    ),
    "workday": generic_portal(
        ["workday.com", "myworkdayjobs.com"],
        [r"/job/[^/]+(?:/|$)"],
    ),
    "ashby": generic_portal(
        ["ashbyhq.com"],
        [r"/[^/]+/[0-9a-f-]{8,}(?:/|$)"],
    ),
    "smartrecruiters": generic_portal(
        ["smartrecruiters.com"],
        [r"/[^/]+/\d+[^/]*(?:/|$)"],
    ),
    "icims": generic_portal(["icims.com"], [r"/jobs/\d+(?:/|$)"]),
    "oraclecloud": generic_portal(
        ["oraclecloud.com"],
        [r"/hcmui/candidateexperience/.*/job/\d+(?:/|$)"],
    ),
    "workable": generic_portal(
        ["workable.com"],
        [r"/[^/]+/j/[0-9a-z-]+(?:/|$)"],
    ),
    "taleo": generic_portal(["taleo.net"]),
    "successfactors": generic_portal(["successfactors.com", "sapsf.com"]),
    "jobvite": generic_portal(["jobvite.com"]),
    "bamboohr": generic_portal(["bamboohr.com"]),
    "ziprecruiter": {
        **generic_portal(
            ["ziprecruiter.com", "ziprecruiter.in"],
            [
                r"/jobs(?:/|$|-)",
                r"/(?:clk/)?c/[^/]+/job/[^/]+",
                r"/job/[^/]+",
                r"/(?:e?km)/[^/]+",
            ],
        ),
        "email_senders": ["ziprecruiter.com", "ziprecruiter.in", "alerts@ziprecruiter.com"],
        "profile_dir": "data/gmail-agent/browser_profiles/ziprecruiter",
        "scraper": "ziprecruiter",
    },
    "seek": generic_portal(
        ["seek.com.au", "s.seek.com.au"],
        [r"/job(?:/|$)", r"/job/\d+(?:/|$)"],
    ),
    "monster": generic_portal(["monster.com"], [r"/jobs?"]),
    "careerbuilder": generic_portal(["careerbuilder.com"], [r"/jobs?"]),
    "monstergulf": generic_portal(["monstergulf.com"]),
    "laimoon": generic_portal(["laimoon.com"]),
    "mihnati": generic_portal(["mihnati.com"]),
    "timesjobs": generic_portal(["timesjobs.com"]),
    "shine": generic_portal(["shine.com"]),
    "instahyre": generic_portal(["instahyre.com"]),
    "stepstone": generic_portal(
        ["stepstone.de"],
        [r"/stellenangebote(?:--|/)"],
    ),
    "xing": generic_portal(["xing.com"], [r"/jobs/"]),
    "eures": generic_portal(["eures.europa.eu"]),
    "arbeitsagentur": generic_portal(
        ["arbeitsagentur.de"],
        [r"/jobsuche"],
    ),
    "arbeitnow": generic_portal(["arbeitnow.com"]),
    "wellfound": generic_portal(
        ["wellfound.com"],
        [r"/jobs/\d+(?:-|/|$)"],
    ),
    "remoteok": generic_portal(["remoteok.com"]),
    "weworkremotely": generic_portal(["weworkremotely.com"]),
    "flexjobs": generic_portal(["flexjobs.com"]),
    "otta": generic_portal(["otta.com"]),
    "dice": generic_portal(["dice.com"]),
    "builtin": generic_portal(["builtin.com"]),
    "ai_jobs": generic_portal(["ai-jobs.net"]),
}
